name: push to staging environment
on: 
  push:
    branches: [ "staging" ]
  pull_request: 
    branches: ["staging" ]
jobs: 
  pull-app:
    runs-on: ubuntu-latest
    steps: 
    - name: setup aws credentials so we can pull the app from s3 bucket
      run: ssh -i {{secrets.SECRETS}} {{secrets.USER}}@{{secrets.IP}} sh ./script.sh
      
