name: deploy go app
on: 
  push:
    branches: [ "development" ]
  pull_request: 
    branches: ["development" ]
jobs: 
  build-app:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
    - uses: actions/setup-go@v3
    - run: go version
    - run: go mod init github.com/thedevopschool/go-app
#     - name: go test
#       run: go test -v . 
    - name: Go build
      run: go build main.go -o thedevopsschool  
    - name: Upload folder to bucket
      uses: a-sync/s3-uploader@master
      with:
        args: --recursive --exclude "*.log"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        S3_KEY: ${{ secrets.S3_KEY }}
        FILE: ./thedevopsschool

  
