name: Go

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: init
        run: go mod init test3
        
      - name: tidy
        run: go mod tidy
        
      - name: get
        run: go get -u github.com/google/go-github/v29
        
      - name: Build
        run: go build -v 1.19

      - name: Test
        run: go test -v 1.19
