name: Deploy Go artifact to production

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout production branch
      uses: actions/checkout@v2
      with:
        ref: production

    - name: aws crendentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download artifact from S3 bucket
      run: |
        aws s3 cp s3://godeploystaging/github.com/TheDevOpsSchool/testing-the-go-app-go-app-1/edit/production/.github/workflows/ci.yml/main.go


    - name: Commit and push changes
      run: |
        git config --global user.email "dornubari2002@gmail.comcom"
        git config --global user.name "Dornubari"
        git add .
        git commit -m "Deploy my Go artifact"
        git push
      env:
        CI: true
