name: Deploy Go artifact to production

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout production branch
      uses: actions/checkout@v2
      with:
        ref: production

    - name: Download artifact from S3
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Fetch artifact from S3
      uses: aws-actions/amazon-s3-fetch-object-action@v2
      with:
        aws-region: us-east-1
        bucket-name: godeploystaging
        object-key: staging

    #- name: Build and deploy Go artifact
     # run: |
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: dornubari/main.go
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    #- name: Create SSH key
     # run: ssh-keygen -t rsa -b 4096 -f ./deploy_key -N ''

    #- name: Add SSH key to SSH agent
    ## with:
      #  ssh-private-key: ./deploy_key

   ## uses: appleboy/ssh-action@v0.1.8
     # with:
        #host: ${{ secrets.EC2_HOST }}
        #username: ${{ secrets.EC2_USER }}
        #script: |
          #docker stop my-go-app || true
         # docker rm my-go-app || true
          #docker pull my-dockerhub-username/my-go-app:latest
          #docker run -d --name my-go-app -p 8080:8080 my-dockerhub-username/my-go-app:latest
    - name: Download artifact from S3 bucket
      run: |
        aws s3 cp s3://<godeploystaging>/<Amazon S3/Buckets/godeploystaging/staging/> <Home> --recursive


    - name: Commit and push changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Deploy my Go artifact"
        git push
      env:
        CI: true
